# Generated by Django 6.0.6 on 2026-06-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='correo',
        ),
    ]
